version: "26.0.0"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres2
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bus
    ports:
      - "5434:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=youssefardanij@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=0401
    ports:
      - "5050:80"
